### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WordlessEcho** [WordlessEcho/CJK-Fonts-for-Android#1]
- [x] Add 'b' prefix during the comparing of ttc_utils.py in nototools（nototools里两个b的bytes if判断）
- [x] Add tool_path parameter to ttcfile_extract, ttLib.TTFont and ttc_utils.ttcfile_build（指定路径）
- [x] Font names as arguments（把要改的字体文件当作命令行参数传进去）
- [ ] Fix index order may changed after edited（稳定index顺序）
- [x] Output file name not right（修复输出文件的文件名）
- [ ] Multithreading support（多线程）
- [ ] Doing contextual-spacing after extract（把contextual-spacing一起做了）
- [ ] Make a Workflow to edit Noto CJK（做一个Workflow全自动维护一个改过的Noto CJK）
- [ ] Codepoints to be removed as a file (json)?（允许以配置文件方式指定要移除的codepoints？）
- [ ] Remove glyph also?（同时移除字符本身？）
